name: release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: polaris-trade/ci/.github/workflows/release.yml@main
    secrets:
      release-plz-token:              ${{ secrets.RELEASE_PLZ_TOKEN }}
